Jenn/threadsafe enhancer
reduxkotlin/redux-kotlin pull request #78
Opened 2021-05-02 20:21 UTC by jennkao

Following up on issue https://github.com/reduxkotlin/redux-kotlin/issues/77, this PR creates a new enhancer called `synchronizeStore` that wraps a Redux store in a synchronization object. 

I wrote a couple tests to compare the original thread-safe store implementation that we were working with against the proposed method of using the `synchronizeStore` enhancer. The test involves thunk middleware as well as delays to mimic async thunks, and the test for the original implementation intermittently fails with the same error we were seeing in our setup. Notably, when using a breakpoint on line 105 of the `CreateThreadSafeStoreSpec` file and running the test for the original implementation in debug mode, I see that we step into the interface defs of the original store methods in `CreateStore`; doing the same with the test for the enhancer implementation sees us step into the interface defs of the synchronized store in `SynchronizedStore`. This suggests to me that with the original implementation, thunks might be accessing the unsynchronized store `dispatch` method.

The failing test was written just for communicating the issue we were seeing, happy to remove this and/or change up the tests as you see fit. This is my first time contributing to this repo so please let me know if I missed anything in terms of contributing standards. Thanks!

2021-08-02 16:06 UTC, patjackson52 requested changes

2021-08-04 03:40 UTC, jennkao commented on redux-kotlin-threadsafe/src/commonMain/kotlin/org/reduxkotlin/Enhancers.kt
> +fun <State> synchronizeStore(): StoreEnhancer<State> {
@patjackson52 updated name to `createSynchronizedStoreEnhancer`

2021-08-04 03:44 UTC, jennkao commented
I removed the failing test that was used to communicate the issue with `createThreadSafeStore` and have left only the test that uses `createSynchronizedStoreEnhancer`

2021-08-05 21:21 UTC, patjackson52 commented
@jennkao ktlint is failing with some unused imports.

2021-09-16 20:11 UTC, jennkao commented
hey @patjackson52 - following up here, do I need to do anything to get the checks to rerun?

2021-09-21 02:39 UTC, patjackson52 approved these changes

2021-09-21 02:40 UTC, merged

2021-09-23 03:59 UTC, patjackson52 commented
@jennkao merged and the snapshots are published.  Would you be interested in making a PR to bump the version so we can publish release artifacts?

2021-09-24 02:54 UTC, jennkao commented
@patjackson52 yeah sure thing! opened a PR here - https://github.com/reduxkotlin/redux-kotlin/pull/91